#!/usr/bin/env bash
set -euo pipefail

REPO="848deepak/Soma"

if ! gh auth status >/dev/null 2>&1; then
  echo "You are not logged in. Run: gh auth login"
  exit 1
fi

create_issue() {
  local title="$1"
  local labels="$2"
  local body="$3"
  local existing
  existing=$(gh issue list --repo "$REPO" --state all --search "in:title \"$title\"" --json title --jq '.[0].title // ""')
  if [[ "$existing" == "$title" ]]; then
    echo "Skipping existing issue: $title"
    return
  fi
  gh issue create --repo "$REPO" --title "$title" --label "$labels" --body "$body"
}

create_issue "Status bar flicker on rapid tab navigation in dark mode" "type:ux,priority:medium,area:ui" "### 🔴 Title:\nStatus bar flicker on rapid tab navigation in dark mode\n\n### 📂 Category:\nUX\n\n### 🚨 Priority:\nMedium\n\n### 🧠 Description:\nStatus bar style is managed per-screen and can flicker during quick navigation.\n\n### 🔁 Steps to Reproduce:\n1. Enable dark mode.\n2. Rapidly switch tabs.\n\n### ✅ Expected Behavior:\nStable status bar style across navigation.\n\n### ❌ Actual Behavior:\nVisible style flicker.\n\n### 💡 Suggested Fix:\nMove status bar ownership to top-level layout and derive style once per theme.\n\n### 📌 Additional Notes:\nAffected file: src/components/ui/Screen.tsx"

create_issue "Setup screen uses hardcoded light input colors in dark mode" "type:ux,type:bug,priority:medium,area:ui" "### 🔴 Title:\nSetup screen uses hardcoded light input colors in dark mode\n\n### 📂 Category:\nUX\n\n### 🚨 Priority:\nMedium\n\n### 🧠 Description:\nInput colors remain light in dark theme and reduce readability/visual consistency.\n\n### 🔁 Steps to Reproduce:\n1. Enable dark mode.\n2. Open setup/onboarding form.\n\n### ✅ Expected Behavior:\nInput containers/text adapt to theme.\n\n### ❌ Actual Behavior:\nLight backgrounds remain in dark mode.\n\n### 💡 Suggested Fix:\nApply theme-aware style tokens for input background, border, and text.\n\n### 📌 Additional Notes:\nAffected file: src/screens/SetupScreen.tsx"

create_issue "Responsive layout gaps on tablet and large-width devices" "type:ux,priority:medium,area:ui" "### 🔴 Title:\nResponsive layout gaps on tablet and large-width devices\n\n### 📂 Category:\nUX\n\n### 🚨 Priority:\nMedium\n\n### 🧠 Description:\nFixed paddings and sizing produce underutilized layouts on larger screens.\n\n### 🔁 Steps to Reproduce:\n1. Run app on tablet-width viewport.\n2. Inspect content density and spacing.\n\n### ✅ Expected Behavior:\nAdaptive spacing and max content width by breakpoint.\n\n### ❌ Actual Behavior:\nPhone-centric spacing applied universally.\n\n### 💡 Suggested Fix:\nUse useWindowDimensions breakpoints and responsive spacing tokens.\n\n### 📌 Additional Notes:\nAffected file: src/components/ui/Screen.tsx"

create_issue "Data-rights admin token check should use constant-time comparison" "type:security,priority:medium,area:security,area:backend" "### 🔴 Title:\nData-rights admin token check should use constant-time comparison\n\n### 📂 Category:\nSecurity\n\n### 🚨 Priority:\nMedium\n\n### 🧠 Description:\nDirect string comparison for secrets may leak timing differences.\n\n### 🔁 Steps to Reproduce:\n1. Review token comparison implementation in admin endpoint.\n\n### ✅ Expected Behavior:\nConstant-time comparison for secret validation.\n\n### ❌ Actual Behavior:\nStandard string comparison is used.\n\n### 💡 Suggested Fix:\nAdopt timing-safe comparison utility for token checks.\n\n### 📌 Additional Notes:\nAffected file: supabase/functions/process-data-rights-request/index.ts"

create_issue "Edge functions missing request body size limits" "type:security,priority:medium,area:backend,area:security" "### 🔴 Title:\nEdge functions missing request body size limits\n\n### 📂 Category:\nSecurity\n\n### 🚨 Priority:\nMedium\n\n### 🧠 Description:\nUnbounded JSON parsing can increase memory/DoS risk.\n\n### 🔁 Steps to Reproduce:\n1. Send oversized payloads to function endpoints.\n\n### ✅ Expected Behavior:\nRequests above max payload are rejected with 413.\n\n### ❌ Actual Behavior:\nNo explicit payload cap enforced.\n\n### 💡 Suggested Fix:\nAdd content-length/body-size guards in all edge function handlers.\n\n### 📌 Additional Notes:\nAffected files: supabase/functions/*/index.ts"

create_issue "Cycle length validation missing before mutation submission" "type:bug,priority:medium,area:period" "### 🔴 Title:\nCycle length validation missing before mutation submission\n\n### 📂 Category:\nBug\n\n### 🚨 Priority:\nMedium\n\n### 🧠 Description:\nClient can submit cycle values outside expected constraints, leading to DB rejections and poor UX.\n\n### 🔁 Steps to Reproduce:\n1. Submit out-of-range cycle values from settings/actions flow.\n\n### ✅ Expected Behavior:\nClient-side bounds validation with clear errors before submit.\n\n### ❌ Actual Behavior:\nValidation is inconsistent and may fail late.\n\n### 💡 Suggested Fix:\nApply shared validation schema before all cycle writes.\n\n### 📌 Additional Notes:\nAffected file: hooks/useCycleActions.ts"

create_issue "Inconsistent invalid-JSON handling across edge functions" "type:bug,priority:medium,area:backend" "### 🔴 Title:\nInconsistent invalid-JSON handling across edge functions\n\n### 📂 Category:\nBug\n\n### 🚨 Priority:\nMedium\n\n### 🧠 Description:\nSome handlers fail gracefully on bad JSON while others can throw and return opaque 500s.\n\n### 🔁 Steps to Reproduce:\n1. POST malformed JSON to each function endpoint.\n\n### ✅ Expected Behavior:\nAll endpoints return structured 400 invalid-json errors.\n\n### ❌ Actual Behavior:\nError behavior is inconsistent across endpoints.\n\n### 💡 Suggested Fix:\nCentralize JSON parsing/validation middleware and reuse everywhere.\n\n### 📌 Additional Notes:\nAffected files: supabase/functions/*/index.ts"

create_issue "Cycle day integrity should be DB-enforced, not only app-calculated" "type:architecture,priority:medium,area:period,area:backend" "### 🔴 Title:\nCycle day integrity should be DB-enforced, not only app-calculated\n\n### 📂 Category:\nArchitecture\n\n### 🚨 Priority:\nMedium\n\n### 🧠 Description:\ncycle_day relies on app calculation; integrity can drift with orphaned/misaligned records.\n\n### 🔁 Steps to Reproduce:\n1. Inspect daily log inserts and cycle linkage behaviors.\n\n### ✅ Expected Behavior:\nDatabase trigger/constraint enforces cycle_day correctness.\n\n### ❌ Actual Behavior:\nIntegrity depends primarily on client logic.\n\n### 💡 Suggested Fix:\nAdd DB-level generated/triggered cycle_day validation from cycle start date.\n\n### 📌 Additional Notes:\nAffected files: supabase/schema.sql, hooks/useSaveLog.ts"

create_issue "Notification deduplication key accepted but not enforced" "type:architecture,priority:medium,area:notifications,area:backend" "### 🔴 Title:\nNotification deduplication key accepted but not enforced\n\n### 📂 Category:\nArchitecture\n\n### 🚨 Priority:\nMedium\n\n### 🧠 Description:\ndedupeKey is captured but not used to prevent duplicate notification emissions.\n\n### 🔁 Steps to Reproduce:\n1. Trigger same notification payload multiple times with same dedupe key.\n\n### ✅ Expected Behavior:\nSubsequent duplicate requests are ignored/idempotent.\n\n### ❌ Actual Behavior:\nDuplicates can still be sent.\n\n### 💡 Suggested Fix:\nEnforce unique dedupe key policy and idempotent send pipeline.\n\n### 📌 Additional Notes:\nAffected files: supabase/functions/send-fcm*.ts"

create_issue "Legacy send-fcm v1 function should be removed after v2 migration" "type:architecture,priority:low,area:notifications,area:backend" "### 🔴 Title:\nLegacy send-fcm v1 function should be removed after v2 migration\n\n### 📂 Category:\nArchitecture\n\n### 🚨 Priority:\nLow\n\n### 🧠 Description:\nv1 and v2 coexistence increases confusion and accidental routing risks.\n\n### 🔁 Steps to Reproduce:\n1. Inspect deployed function set and invocation paths.\n\n### ✅ Expected Behavior:\nSingle canonical notification sender implementation.\n\n### ❌ Actual Behavior:\nDeprecated path remains present.\n\n### 💡 Suggested Fix:\nDeprecate and delete v1 after confirming all callers migrated to v2.\n\n### 📌 Additional Notes:\nAffected file: supabase/functions/send-fcm/index.ts"

create_issue "Daily logs retrieval lacks pagination and selective fields" "type:architecture,priority:low,area:logging,area:backend" "### 🔴 Title:\nDaily logs retrieval lacks pagination and selective fields\n\n### 📂 Category:\nPerformance\n\n### 🚨 Priority:\nLow\n\n### 🧠 Description:\nWide selects over long ranges increase payload size and render cost.\n\n### 🔁 Steps to Reproduce:\n1. Load log-heavy account and inspect network payload/query time.\n\n### ✅ Expected Behavior:\nPaginated fetch with narrowed fields per screen need.\n\n### ❌ Actual Behavior:\nHeavy fetch strategy used by default.\n\n### 💡 Suggested Fix:\nAdopt pagination + projection-based queries in log hooks.\n\n### 📌 Additional Notes:\nAffected file: hooks/useDailyLogs.ts"

create_issue "Error responses expose too much internal detail in edge handlers" "type:security,priority:low,area:backend,area:security" "### 🔴 Title:\nError responses expose too much internal detail in edge handlers\n\n### 📂 Category:\nSecurity\n\n### 🚨 Priority:\nLow\n\n### 🧠 Description:\nReturning raw backend error messages can leak internals.\n\n### 🔁 Steps to Reproduce:\n1. Force handler errors and inspect response payloads.\n\n### ✅ Expected Behavior:\nGeneric client errors + server-side structured logging.\n\n### ❌ Actual Behavior:\nSome responses include internal error strings.\n\n### 💡 Suggested Fix:\nStandardize error mapper with safe client payloads and correlation IDs.\n\n### 📌 Additional Notes:\nAffected files: supabase/functions/*/index.ts"

create_issue "Notification invoke path lacks timeout fencing and retry policy" "type:architecture,priority:medium,area:notifications,area:backend" "### 🔴 Title:\nNotification invoke path lacks timeout fencing and retry policy\n\n### 📂 Category:\nPerformance\n\n### 🚨 Priority:\nMedium\n\n### 🧠 Description:\nLong/hanging downstream invocations can stall scheduler throughput without bounded timeout handling.\n\n### 🔁 Steps to Reproduce:\n1. Simulate delayed sender responses.\n2. Observe scheduler completion behavior.\n\n### ✅ Expected Behavior:\nBounded invoke timeout + retry/backoff policy.\n\n### ❌ Actual Behavior:\nScheduler can be blocked by slow calls.\n\n### 💡 Suggested Fix:\nWrap invokes with Promise.race timeout and structured retry budget.\n\n### 📌 Additional Notes:\nAffected file: supabase/functions/process-scheduled-notifications/index.ts"

create_issue "Partner permission model can drift between profile defaults and link snapshot" "type:architecture,priority:medium,area:security,area:backend" "### 🔴 Title:\nPartner permission model can drift between profile defaults and link snapshot\n\n### 📂 Category:\nArchitecture\n\n### 🚨 Priority:\nMedium\n\n### 🧠 Description:\nPermission values appear to exist in multiple places and can diverge after updates.\n\n### 🔁 Steps to Reproduce:\n1. Link partner with initial permissions.\n2. Change default sharing permissions later.\n3. Compare effective partner access.\n\n### ✅ Expected Behavior:\nExplicitly defined and consistent permission source of truth.\n\n### ❌ Actual Behavior:\nPotential drift/ambiguity in effective permissions.\n\n### 💡 Suggested Fix:\nDefine immutable-vs-dynamic policy and enforce sync strategy with tests.\n\n### 📌 Additional Notes:\nAffected files: supabase/schema.sql, supabase/rls_policies.sql"

create_issue "Notes privacy guarantee should be enforced by policy and tests" "type:security,priority:medium,area:security,area:backend" "### 🔴 Title:\nNotes privacy guarantee should be enforced by policy and tests\n\n### 📂 Category:\nSecurity\n\n### 🚨 Priority:\nMedium\n\n### 🧠 Description:\nComments/documentation indicate notes are private, but this guarantee should be policy- and test-enforced.\n\n### 🔁 Steps to Reproduce:\n1. Audit partner-facing views/policies for notes field exposure.\n\n### ✅ Expected Behavior:\nNotes excluded by enforced policy + automated tests.\n\n### ❌ Actual Behavior:\nGuarantee may depend on convention rather than enforceable guardrails.\n\n### 💡 Suggested Fix:\nAdd explicit policy constraints and regression tests preventing notes exposure.\n\n### 📌 Additional Notes:\nAffected files: supabase/schema.sql, supabase/rls_policies.sql"

create_issue "Launch bootstrap has competing fallback timers causing inconsistent auth/splash transitions" "type:bug,priority:medium,area:ui,area:auth" "### 🔴 Title:\nLaunch bootstrap has competing fallback timers causing inconsistent auth/splash transitions\n\n### 📂 Category:\nBug\n\n### 🚨 Priority:\nMedium\n\n### 🧠 Description:\nMultiple timeout fallbacks in launch/auth bootstrap path can produce early unblocking and transition artifacts.\n\n### 🔁 Steps to Reproduce:\n1. Simulate slow auth/network startup.\n2. Observe transition timing between splash and routed content.\n\n### ✅ Expected Behavior:\nSingle deterministic timeout strategy with consistent user state transition.\n\n### ❌ Actual Behavior:\nCompeting timers can cause inconsistent launch behavior.\n\n### 💡 Suggested Fix:\nConsolidate bootstrap timeout policy and gate transitions on explicit readiness state.\n\n### 📌 Additional Notes:\nAffected files: app/_layout.tsx, src/components/ui/SomaLoadingSplash.tsx"

echo "Remaining issue creation run complete."
